### PR TITLE
Updated German translation (0.0.9)

### PR DESCRIPTION
**Pull request by ACGaming**

### CODE REVIEW

**Comment by mcpecommander** [comment]
Thanks dude. But I added tons of new subtitles for the 0.1 update coming on this sunday. I accepted the translation anyway

**Comment by mcpecommander** [comment]
I will try to push a commit for the translation if you want to update them before the update comes. Thanks again

**Comment by ACGaming** [comment]
Up to you!

**Comment by mcpecommander** [comment]
I committed the last translation file. You can try to translate it before sunday if you want to but be warned it is huge.

**Comment by ACGaming** [comment]
It is huge indeed! Don't know if I'll translate it before sunday, but thanks either way. 🙂

**Comment by mcpecommander** [comment]
I added the full JEI integration, so technically not every translation is in the game if JEI is not installed

**Pull request merged**
